### ISSUE TITLE
Template' object is not iterable

### ISSUE THREAD

**Issue by acarmisc** [vintasoftware/django-templated-email#46] opened 2015-05-10 20:03 UTC
Hi, when I try to send a mail I got 
    ``Template' object is not iterable``

I found in utils.py this part:
    ``for node in template``

but template is not a list. Instead I can fix and get app running if I make something like:

   ``for node in template.template.nodelist:``

It's my problem? Anyone else?

Thanks.

**Comment by rosscdh** [comment] 2015-05-21 12:47
+1

appears to be caused by changes to the templates in django 1.8.

the utils._get_node needs to be updated to support the new template object I suspect

**Comment by chuchiperriman** [comment] 2015-05-22 15:40
+1
Same problem here

**Comment by chuchiperriman** [comment] 2015-05-22 17:17
It does not work the the @acarmisc change, a new error appear:

    'NoneType' object has no attribute 'engine'

**Comment by acarmisc** [comment] 2015-05-22 19:26
I've got it working with that workaround. Witch version are you using?

**Comment by chuchiperriman** [comment] 2015-05-23 09:41
The last git code of templated_email and django 1.8.2 with the default background

**Comment by chuchiperriman** [comment] 2015-05-26 08:27
Complete trace:

```
Traceback (most recent call last):
  File "/var/www/.virtualenvs/pymasterdt/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/www/.virtualenvs/pymasterdt/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/django/projects/pymasterdt/difusiones/tasks.py", line 16, in task_notificar_difusion
    ha guardado el nuevo estado y no podemos ver el anterior por eso nos lo
  File "/var/django/projects/pymasterdt/difusiones/manager.py", line 154, in notificar_difusion
    'asunto': asunto
  File "/var/django/projects/pymasterdt/templated_email/__init__.py", line 83, in send_templated_mail
    headers=headers, **kwargs)
  File "/var/django/projects/pymasterdt/templated_email/backends/vanilla_django.py", line 179, in send
    file_extension=file_extension)
  File "/var/django/projects/pymasterdt/templated_email/backends/vanilla_django.py", line 112, in get_email_message
    template_suffix or file_extension)
  File "/var/django/projects/pymasterdt/templated_email/backends/vanilla_django.py", line 76, in _render_email
    response[part] = _get_node(multi_part, render_context, name=part)
  File "/var/django/projects/pymasterdt/templated_email/utils.py", line 30, in _get_node
    return _iter_nodes(template, context, name, block_lookups)
  File "/var/django/projects/pymasterdt/templated_email/utils.py", line 19, in _iter_nodes
    return node.render(context)
  File "/var/www/.virtualenvs/pymasterdt/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 56, in render
    result = self.nodelist.render(context)
  File "/var/www/.virtualenvs/pymasterdt/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/var/www/.virtualenvs/pymasterdt/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/var/www/.virtualenvs/pymasterdt/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 214, in render
    if context.template.engine.debug:
AttributeError: 'NoneType' object has no attribute 'engine'
```

**Comment by chuchiperriman** [comment] 2015-05-28 16:05
hmmm It works for me now, the git code without any change...

**Comment by bastibense** [comment] 2015-06-13 16:30
Had the same issue with the latest version that comes with pip at this moment (0.4.9 released in 2013?!). After checking out the current HEAD from here the problems are gone. I guess the issue here is that most people work with a terribly outdated version of django-templated-email whenever they install it via pip/easy_install. Please fix.

**Comment by kolyaflash** [comment] 2015-09-07 09:24
Please update the pip version.

**Comment by chris-erickson** [comment] 2016-01-15 02:52
I can confirm that this solves my problem too, when updating to Django 1.8.7 (from 1.6.11 in my case).  Replace the proper line in your `requirements.txt` like so, updating the commit as needed:

Old:
```
django-templated-email==0.4.9
```

New:
```
-e git://github.com/BradWhittington/django-templated-email.git@b993f2d3562fca490dc19a2607dc4e3ea6878917#egg=django-templated-email
```

**Comment by Chipmunk-djng** [comment] 2016-01-26 16:55
Facing the same issue as @acarmisc and the fix what he provided. Can we fork this and do a pull request to a the trunk?

**Comment by aericson** [comment] 2016-07-12 00:19
This should be fixed.

**Closed by aericson** 2016-07-12 00:19 UTC
